[phases.setup]
nixPkgs = ['nodejs_18']
aptPkgs = ['curl']
cmds = [
  'corepack enable',
  'corepack prepare pnpm@9.15.9 --activate'
]

[phases.install]
cmds = ['pnpm install --frozen-lockfile']

[phases.build]
cmds = ['pnpm run build']

[phases.start]
cmd = 'pnpm start'
