[phases.setup]
nixpkgsArchive = "2024-04-01"

[phases.setup.environment]
NODE_VERSION = "18.20.8"

[phases.install]
cmds = ["pnpm install"]

[phases.build]
cmds = ["pnpm run build"]

[phases.start]
cmd = "pnpm start"
